(() => {
  'use strict';
  const $q=s=>document.querySelector(s),$$q=s=>[...document.querySelectorAll(s)];
  const brandSmall=$q('.brand small');if(brandSmall)brandSmall.textContent='v2.2 • Android TV 12 • virtual chips only';
  const vipTitle=$q('#vip h2');if(vipTitle)vipTitle.textContent='Premium 3D Light v2.2';
  const style=document.createElement('style');style.textContent=`
  .betPanel{display:flex;align-items:center;justify-content:center;gap:8px;flex-wrap:wrap;margin:8px 0 14px;padding:9px 12px;border:1px solid #ffd86b28;border-radius:16px;background:#080b12bb}.betPanel .betLabel{color:#c8d0dc;font-weight:800}.betValue{min-width:92px;text-align:center;padding:9px 12px;border-radius:12px;background:#131923;border:1px solid #ffd86b45;color:#ffd86b;font-weight:1000;font-size:18px}.betPreset{padding:9px 12px}
  #billiards .stage{min-height:0;padding:12px;overflow:visible}#billiards .center{min-height:0;display:block}#billiards .poolShell{width:100%;max-width:none;overflow:visible}.poolViewport{position:relative;width:100%;padding:8px 8px 14px;perspective:1500px;overflow:visible}#poolCanvas{width:100%!important;height:auto!important;max-height:none!important;display:block;margin:0 auto;border:none!important;border-radius:26px;box-shadow:0 24px 55px #000b;transform-origin:50% 50%;transition:transform .55s ease}.cameraHud{display:flex;justify-content:center;align-items:center;gap:8px;flex-wrap:wrap;margin:10px 0 4px}.cameraHud .camStatus{min-width:150px;text-align:center;color:#ffd86b;font-weight:900}.poolControlsV22{display:grid;grid-template-columns:150px 1fr 170px;gap:14px;align-items:center;margin-top:10px}.poolPadV22{display:grid;grid-template-columns:52px 52px 52px;grid-template-rows:48px 48px 48px;gap:6px;justify-content:center}.poolPadV22 button{padding:0;min-width:0;font-size:26px}.poolPadV22 .up{grid-column:2;grid-row:1}.poolPadV22 .left{grid-column:1;grid-row:2}.poolPadV22 .ok{grid-column:2;grid-row:2}.poolPadV22 .right{grid-column:3;grid-row:2}.poolPadV22 .down{grid-column:2;grid-row:3}.swingGauge{position:relative;height:126px;border-radius:20px;background:radial-gradient(circle at 50% 100%,#242c3a,#090b11 70%);border:1px solid #ffffff24;padding:10px 20px 8px;overflow:hidden}.swingTitle{text-align:center;color:#ffd86b;font-weight:1000;margin-bottom:5px}.swingArc{position:relative;width:min(480px,100%);height:72px;margin:auto}.swingArc:before{content:'';position:absolute;left:8%;right:8%;bottom:-28px;height:110px;border:10px solid transparent;border-top-color:#64e59a;border-left-color:#64e59a;border-right-color:#ff6d7a;border-radius:50% 50% 0 0;transform:rotate(180deg);opacity:.92}.swingNeedle{position:absolute;left:50%;bottom:4px;width:4px;height:62px;background:#fff;box-shadow:0 0 10px #fff;transform-origin:50% 100%;transform:rotate(-62deg);border-radius:3px}.swingHub{position:absolute;left:50%;bottom:0;width:17px;height:17px;transform:translate(-50%,50%);border-radius:50%;background:#ffd86b;border:3px solid #fff}.swingTicks{display:flex;justify-content:space-between;padding:0 9%;margin-top:-2px;font-weight:1000;color:#e4e9ef}.swingTicks span:last-child{color:#ff747e}.swingReadout{text-align:center;margin-top:2px;color:#b7c0cd;font-size:13px}.poolRule{padding:10px 12px;border-radius:12px;background:#080b12;border:1px solid #ffffff14;color:#c8d0dc;text-align:center;font-size:13px}.poolRule b{color:#ffd86b}@media(max-width:900px){.poolControlsV22{grid-template-columns:126px 1fr 138px;gap:8px}.poolPadV22{grid-template-columns:46px 46px 46px;grid-template-rows:44px 44px 44px}.swingGauge{height:118px;padding-left:10px;padding-right:10px}}`;
  document.head.appendChild(style);

  const betState={slots:+(localStorage.getItem('k3d_bet_slots')||50),poker:+(localStorage.getItem('k3d_bet_poker')||100),baccarat:+(localStorage.getItem('k3d_bet_baccarat')||100),keno:+(localStorage.getItem('k3d_bet_keno')||50),horses:+(localStorage.getItem('k3d_bet_horses')||100),sports:+(localStorage.getItem('k3d_bet_sports')||100)};
  const clampBet=v=>Math.max(10,Math.min(1000,Math.round(v/10)*10));
  function refreshBetLabels(){const sb=$q('#spinBtn');if(sb)sb.textContent=`SPIN • ${betState.slots}`;const nh=$q('#newHand');if(nh)nh.textContent=`ΝΕΟ ΧΕΡΙ • ${betState.poker}`;const dk=$q('#drawKeno');if(dk)dk.textContent=`ΚΛΗΡΩΣΗ • ${betState.keno}`;const rb=$q('#raceBtn');if(rb)rb.textContent=`ΕΚΚΙΝΗΣΗ • ${betState.horses}`;$$q('.bacBet').forEach(b=>b.textContent=`${b.dataset.bet.toUpperCase()} • ${betState.baccarat}`);$$q('.slotStats span').forEach(s=>{if(s.textContent.startsWith('BET:'))s.textContent=`BET: ${betState.slots}`})}
  function setBet(k,v){betState[k]=clampBet(v);localStorage.setItem('k3d_bet_'+k,betState[k]);const o=$q(`[data-bet-value="${k}"]`);if(o)o.textContent=betState[k].toLocaleString('el-GR');refreshBetLabels()}
  function makeBetPanel(screenId,key){const screen=$q('#'+screenId);if(!screen||screen.querySelector('.betPanel'))return;const bar=screen.querySelector('.bar');if(!bar)return;const panel=document.createElement('div');panel.className='betPanel';panel.innerHTML=`<span class="betLabel">ΠΟΝΤΑΡΙΣΜΑ</span><button class="btn betMinus" data-bet-key="${key}">−10</button><span class="betValue" data-bet-value="${key}">${betState[key]}</span><button class="btn betPlus" data-bet-key="${key}">+10</button><button class="btn betPreset" data-bet-key="${key}" data-bet-preset="50">50</button><button class="btn betPreset" data-bet-key="${key}" data-bet-preset="100">100</button><button class="btn betPreset" data-bet-key="${key}" data-bet-preset="250">250</button><button class="btn betPreset" data-bet-key="${key}" data-bet-preset="500">500</button>`;bar.insertAdjacentElement('afterend',panel)}
  [['slots','slots'],['poker','poker'],['baccarat','baccarat'],['keno','keno'],['horses','horses'],['sports','sports']].forEach(x=>makeBetPanel(x[0],x[1]));
  $$q('.betMinus').forEach(b=>b.onclick=()=>setBet(b.dataset.betKey,betState[b.dataset.betKey]-10));$$q('.betPlus').forEach(b=>b.onclick=()=>setBet(b.dataset.betKey,betState[b.dataset.betKey]+10));$$q('.betPreset').forEach(b=>b.onclick=()=>setBet(b.dataset.betKey,+b.dataset.betPreset));refreshBetLabels();

  const slotBtn=$q('#spinBtn');if(slotBtn)slotBtn.onclick=()=>{const bet=betState.slots;try{if(!pay(bet))return}catch(e){return}const box=$q('#reels5'),reels=$$q('#reels5 .reel'),syms=['🍒','🍋','🔔','7️⃣','💎','⭐'];box.classList.add('spinning');const tickers=reels.map((r,i)=>setInterval(()=>{r.textContent=syms[Math.floor(Math.random()*syms.length)];r.style.transform=`rotateX(${(Date.now()/3+i*53)%360}deg)`},55+i*7));$q('#slotResult').textContent='Γυρίζουν...';setTimeout(()=>{tickers.forEach(clearInterval);const a=reels.map(r=>{r.style.transform='';const s=syms[Math.floor(Math.random()*syms.length)];r.textContent=s;return s});box.classList.remove('spinning');const counts={};a.forEach(s=>counts[s]=(counts[s]||0)+1);const wild=counts['⭐']||0,scatter=counts['💎']||0,best=Math.max(...Object.values(counts));let mult=0;if(scatter>=3)mult+=scatter*3.6;if(best+wild>=5)mult+=36;else if(best+wild>=4)mult+=12;else if(best+wild>=3)mult+=3.6;if(a.every(s=>s==='7️⃣'))mult=100;const prize=Math.round(bet*mult);if(prize){try{reward(prize)}catch(e){};$q('#slotResult').innerHTML=`<span class="win">Κέρδος ${prize.toLocaleString('el-GR')} μαρκών!</span>`}else $q('#slotResult').innerHTML='<span class="lose">Χωρίς πληρωμή σε αυτή την περιστροφή.</span>'},1050)};

  const newHandBtn=$q('#newHand');if(newHandBtn)newHandBtn.onclick=()=>{const bet=betState.poker;try{if(!pay(bet))return}catch(e){return}const d=freshDeck(),n=pokerMode==='omaha'?4:2;poker={deck:d,me:d.splice(0,n),ai:d.splice(0,n),board:[],stage:0,pot:bet*2,baseBet:bet};renderPoker();$q('#pokerStatus').textContent=`Pre-flop • pot ${poker.pot}`};
  $$q('.pokerAct').forEach(b=>b.onclick=()=>{if(!poker){$q('#pokerStatus').textContent='Πάτησε ΝΕΟ ΧΕΡΙ.';return}const act=b.dataset.act;if(act==='fold'){poker=null;$q('#pokerStatus').innerHTML='<span class="lose">Fold.</span>';$q('#aiCards').innerHTML='';return}if(act==='raise'){const raise=Math.max(10,Math.round((poker.baseBet||betState.poker)/2/10)*10);try{if(!pay(raise))return}catch(e){return}poker.pot+=raise*2}if(poker.stage===0){poker.board.push(...poker.deck.splice(0,3));poker.stage=1;$q('#pokerStatus').textContent='FLOP • pot '+poker.pot}else if(poker.stage===1){poker.board.push(poker.deck.shift());poker.stage=2;$q('#pokerStatus').textContent='TURN • pot '+poker.pot}else if(poker.stage===2){poker.board.push(poker.deck.shift());poker.stage=3;$q('#pokerStatus').textContent='RIVER • pot '+poker.pot}else showdown();renderPoker()});

  $$q('.bacBet').forEach(b=>b.onclick=()=>{const bet=betState.baccarat;try{if(!pay(bet))return}catch(e){return}const d=freshDeck(),p=[d.pop(),d.pop()],k=[d.pop(),d.pop()];let pv=(bacVal(p[0])+bacVal(p[1]))%10,kv=(bacVal(k[0])+bacVal(k[1]))%10;if(pv<=5){p.push(d.pop());pv=(pv+bacVal(p[2]))%10}if(kv<=5){k.push(d.pop());kv=(kv+bacVal(k[2]))%10}const res=pv>kv?'player':kv>pv?'banker':'tie';$q('#bacCards').innerHTML='<div><div class="muted">PLAYER '+pv+'</div><div class="cards">'+p.map(ch).join('')+'</div></div><div><div class="muted">BANKER '+kv+'</div><div class="cards">'+k.map(ch).join('')+'</div></div>';if(b.dataset.bet===res){const pr=res==='tie'?bet*9:bet*2;try{reward(pr)}catch(e){};$q('#bacResult').innerHTML='<span class="win">'+res.toUpperCase()+' • +'+pr+'</span>'}else $q('#bacResult').innerHTML='<span class="lose">Κέρδισε '+res.toUpperCase()+'</span>'});

  const kenoBtn=$q('#drawKeno');if(kenoBtn)kenoBtn.onclick=()=>{if(!ks.size){$q('#kenoResult').textContent='Διάλεξε τουλάχιστον 1 αριθμό.';return}const bet=betState.keno;try{if(!pay(bet))return}catch(e){return}$$q('.num').forEach(x=>x.classList.remove('drawn'));const pool=[...Array(80)].map((_,i)=>i+1),draw=[];while(draw.length<20){const j=Math.floor(Math.random()*pool.length);draw.push(pool.splice(j,1)[0])}draw.forEach(n=>$q('#kenoGrid').children[n-1].classList.add('drawn'));const hits=draw.filter(n=>ks.has(n)).length,mult=hits>=5?hits*1.8:hits>=3?hits*.4:0,pr=Math.round(bet*mult);if(pr)try{reward(pr)}catch(e){};$q('#kenoResult').innerHTML='Επιτυχίες <b>'+hits+'</b>/'+ks.size+(pr?' • <span class="win">+'+pr+'</span>':'')};

  const raceBtn=$q('#raceBtn');if(raceBtn)raceBtn.onclick=()=>{const bet=betState.horses;try{if(!pay(bet))return}catch(e){return}const race=$q('#race'),horses=$$q('#race .v21Horse, #race .horse');if(!horses.length)return;race.classList.add('racing');const prog=Array(horses.length).fill(0);let done=false;$q('#raceResult').textContent='Ο αγώνας ξεκίνησε...';const t=setInterval(()=>{for(let i=0;i<prog.length;i++)prog[i]=Math.min(100,prog[i]+1.2+Math.random()*3.6);horses.forEach((h,i)=>{if(h.classList.contains('v21Horse'))h.style.bottom=(18+prog[i]*3.15)+'px';else h.style.left=Math.min(92,prog[i]*.92)+'%'});const wi=prog.findIndex(x=>x>=100);if(wi>=0&&!done){done=true;clearInterval(t);race.classList.remove('racing');const w=wi+1;if(w===horsePick){const pr=bet*5;try{reward(pr)}catch(e){};$q('#raceResult').innerHTML='<span class="win">Νίκησε το Άλογο '+w+' • +'+pr+'</span>'}else $q('#raceResult').innerHTML='<span class="lose">Νίκησε το Άλογο '+w+'</span>'}},110)};
  $$q('.odd').forEach(b=>b.onclick=()=>{const bet=betState.sports;try{if(!pay(bet))return}catch(e){return}const opts=['1','X','2'],res=opts[Math.floor(Math.random()*3)],odd=b.dataset.p==='1'?1.85:b.dataset.p==='X'?3.10:2.15;if(b.dataset.p===res){const pr=Math.round(bet*odd);try{reward(pr)}catch(e){};$q('#sportResult').innerHTML='<span class="win">Αποτέλεσμα '+res+' • +'+pr+'</span>'}else $q('#sportResult').innerHTML='<span class="lose">Αποτέλεσμα '+res+'</span>'});

  let poolModeV22='8ball',firstHitNumber=null,targetBeforeShot=null,pottedThisShot=[],cameraIndex=0,autoCamera=false,autoCameraTimer=null,needlePhase=0,needleDir=1,needlePower=.28,needleRAF=0;
  const poolCanvas=$q('#poolCanvas'),poolShell=$q('#billiards .poolShell');
  if(poolCanvas&&poolShell){poolCanvas.width=1200;poolCanvas.height=650;if(!poolCanvas.parentElement.classList.contains('poolViewport')){const viewport=document.createElement('div');viewport.className='poolViewport';poolCanvas.parentElement.insertBefore(viewport,poolCanvas);viewport.appendChild(poolCanvas)}const oldControls=$q('#poolV21Controls');if(oldControls)oldControls.remove();const oldMeter=poolShell.querySelector('.meter');if(oldMeter)oldMeter.style.display='none';
    const camHud=document.createElement('div');camHud.className='cameraHud';camHud.innerHTML='<button class="btn" id="camPrev">◀ ΚΑΜΕΡΑ</button><span class="camStatus" id="camStatus">ΚΑΜΕΡΑ 1 / ΠΑΝΩ</span><button class="btn" id="camNext">ΚΑΜΕΡΑ ▶</button><button class="btn" id="camAuto">ΠΑΝΟΡΑΜΙΚΗ AUTO</button>';poolCanvas.parentElement.insertAdjacentElement('afterend',camHud);
    const controls=document.createElement('div');controls.id='poolV22Controls';controls.className='poolControlsV22';controls.innerHTML='<div class="poolPadV22"><button class="btn up" data-v22="camPrev">▲</button><button class="btn left" data-v22="aimLeft">◀</button><button class="btn gold ok" data-v22="shoot">OK</button><button class="btn right" data-v22="aimRight">▶</button><button class="btn down" data-v22="camNext">▼</button></div><div class="swingGauge"><div class="swingTitle">ΕΝΤΑΣΗ — ΠΑΤΑ OK ΣΤΟ ΣΗΜΕΙΟ ΠΟΥ ΘΕΛΕΙΣ</div><div class="swingArc"><div class="swingNeedle" id="swingNeedle"></div><div class="swingHub"></div></div><div class="swingTicks"><span>1</span><span>2</span><span>3</span><span>MAX</span></div><div class="swingReadout" id="swingReadout">Ισχύς: 1</div></div><div class="poolRule" id="poolRule"><b>8-BALL</b><br>◀ ▶ στόχος • ▲ ▼ κάμερα • OK χτύπημα</div>';const result=$q('#poolResult');poolShell.insertBefore(controls,result||null);
    const cameraViews=[{name:'ΚΑΜΕΡΑ 1 / ΠΑΝΩ',transform:'perspective(1500px) rotateX(0deg) rotateZ(0deg) scale(.98)'},{name:'ΚΑΜΕΡΑ 2 / ΑΡΙΣΤΕΡΑ',transform:'perspective(1500px) rotateX(11deg) rotateZ(-2.2deg) scale(.94)'},{name:'ΚΑΜΕΡΑ 3 / ΔΕΞΙΑ',transform:'perspective(1500px) rotateX(11deg) rotateZ(2.2deg) scale(.94)'},{name:'ΚΑΜΕΡΑ 4 / ΧΑΜΗΛΑ',transform:'perspective(1300px) rotateX(16deg) rotateZ(0deg) scale(.92)'}];function applyCamera(){const v=cameraViews[cameraIndex];poolCanvas.style.transform=v.transform;$q('#camStatus').textContent=v.name}function prevCamera(){cameraIndex=(cameraIndex+cameraViews.length-1)%cameraViews.length;applyCamera()}function nextCamera(){cameraIndex=(cameraIndex+1)%cameraViews.length;applyCamera()}function toggleAutoCamera(){autoCamera=!autoCamera;const b=$q('#camAuto');if(b)b.classList.toggle('gold',autoCamera);if(autoCamera){clearInterval(autoCameraTimer);autoCameraTimer=setInterval(nextCamera,2200)}else clearInterval(autoCameraTimer)}$q('#camPrev').onclick=prevCamera;$q('#camNext').onclick=nextCamera;$q('#camAuto').onclick=toggleAutoCamera;applyCamera();
    const palette={1:'#f4d13d',2:'#2e6ee9',3:'#d93636',4:'#6a3ac7',5:'#e98b2e',6:'#2aa668',7:'#7c1f29',8:'#111111',9:'#f4d13d',10:'#2e6ee9',11:'#d93636',12:'#6a3ac7',13:'#e98b2e',14:'#2aa668',15:'#7c1f29'};function makeBall(n,x,y){return{n,x,y,vx:0,vy:0,c:n===0?'#fff':palette[n]||'#eee',stripe:n>=9}}function rack8(){const arr=[1,9,2,10,8,3,11,4,12,5,13,6,14,7,15],out=[];let k=0;for(let row=0;row<5;row++)for(let j=0;j<=row;j++)out.push(makeBall(arr[k++],805+row*27,325-row*13.5+j*27));return out}function rack9(){const nums=[1,2,3,4,9,5,6,7,8],spots=[[805,325],[832,311.5],[832,338.5],[859,298],[859,325],[859,352],[886,311.5],[886,338.5],[913,325]];return nums.map((n,i)=>makeBall(n,spots[i][0],spots[i][1]))}function lowestNine(){const ns=balls.filter(b=>b.n>0&&b.n<=9).map(b=>b.n);return ns.length?Math.min(...ns):null}
    resetPool=function(){balls=[];balls.push(makeBall(0,300,325));balls.push(...(poolModeV22==='9ball'?rack9():rack8()));aim=0;anim=false;firstHitNumber=null;pottedThisShot=[];targetBeforeShot=null;drawPool();const rule=$q('#poolRule');if(rule)rule.innerHTML=poolModeV22==='9ball'?'<b>9-BALL</b><br>Χτυπάς πρώτα τη μικρότερη μπάλα • η 9 κερδίζει όταν μπει νόμιμα':'<b>8-BALL</b><br>Πλήρες τραπέζι • 15 μπάλες • ◀ ▶ στόχος • ▲ ▼ κάμερα';const r=$q('#poolResult');if(r)r.textContent=poolModeV22==='9ball'?'Στόχος: πρώτα η μπάλα 1.':'Έτοιμο για σπάσιμο.'};
    drawPool=function(){const c=ctx,W=poolCanvas.width,H=poolCanvas.height;c.clearRect(0,0,W,H);c.fillStyle='#2b160b';c.fillRect(0,0,W,H);const grad=c.createLinearGradient(0,0,W,H);grad.addColorStop(0,'#7a4a20');grad.addColorStop(.5,'#3c210f');grad.addColorStop(1,'#8a5729');c.fillStyle=grad;c.fillRect(22,22,W-44,H-44);c.fillStyle='#163c2e';c.fillRect(62,62,W-124,H-124);const cloth=c.createRadialGradient(W*.48,H*.45,20,W*.5,H*.5,W*.65);cloth.addColorStop(0,'#13765a');cloth.addColorStop(1,'#07503c');c.fillStyle=cloth;c.fillRect(78,78,W-156,H-156);const pockets=[[78,78],[W/2,72],[W-78,78],[78,H-78],[W/2,H-72],[W-78,H-78]];c.fillStyle='#020202';pockets.forEach(([x,y])=>{c.beginPath();c.arc(x,y,25,0,Math.PI*2);c.fill()});c.fillStyle='#e6cf91';for(let i=1;i<7;i++){c.beginPath();c.arc(78+i*(W-156)/7,52,4,0,Math.PI*2);c.fill();c.beginPath();c.arc(78+i*(W-156)/7,H-52,4,0,Math.PI*2);c.fill()}for(let i=1;i<3;i++){c.beginPath();c.arc(52,78+i*(H-156)/3,4,0,Math.PI*2);c.fill();c.beginPath();c.arc(W-52,78+i*(H-156)/3,4,0,Math.PI*2);c.fill()}c.strokeStyle='rgba(255,255,255,.12)';c.lineWidth=2;c.beginPath();c.moveTo(W*.25,78);c.lineTo(W*.25,H-78);c.stroke();c.beginPath();c.arc(W*.75,H/2,4,0,Math.PI*2);c.fillStyle='rgba(255,255,255,.45)';c.fill();for(const b of balls){c.save();c.shadowColor='rgba(0,0,0,.45)';c.shadowBlur=7;c.shadowOffsetX=3;c.shadowOffsetY=5;c.beginPath();c.arc(b.x,b.y,13,0,Math.PI*2);c.fillStyle=b.c;c.fill();c.shadowColor='transparent';if(b.n>0){if(b.stripe){c.save();c.beginPath();c.arc(b.x,b.y,12,0,Math.PI*2);c.clip();c.fillStyle='#f4f1e8';c.fillRect(b.x-13,b.y-13,26,8);c.fillRect(b.x-13,b.y+5,26,8);c.restore()}c.beginPath();c.arc(b.x,b.y,7,0,Math.PI*2);c.fillStyle='#f7f4ec';c.fill();c.fillStyle='#111';c.font='bold 9px sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillText(String(b.n),b.x,b.y+.5)}else{const hi=c.createRadialGradient(b.x-5,b.y-6,1,b.x,b.y,13);hi.addColorStop(0,'#fff');hi.addColorStop(1,'#cfd3d6');c.fillStyle=hi;c.beginPath();c.arc(b.x,b.y,12.5,0,Math.PI*2);c.fill()}c.restore()}const cue=balls.find(b=>b.n===0);if(cue&&!anim){c.strokeStyle='#f3d19b';c.lineWidth=6;c.beginPath();c.moveTo(cue.x-Math.cos(aim)*205,cue.y-Math.sin(aim)*205);c.lineTo(cue.x-Math.cos(aim)*28,cue.y-Math.sin(aim)*28);c.stroke();c.strokeStyle='rgba(255,255,255,.72)';c.lineWidth=2;c.setLineDash([10,9]);c.beginPath();c.moveTo(cue.x,cue.y);c.lineTo(cue.x+Math.cos(aim)*380,cue.y+Math.sin(aim)*380);c.stroke();c.setLineDash([])}};
    const pocketCenters=()=>[[78,78],[600,72],[1122,78],[78,572],[600,578],[1122,572]],inPocket=b=>pocketCenters().some(([x,y])=>Math.hypot(b.x-x,b.y-y)<28);function endShot(){anim=false;const cueMissing=!balls.some(b=>b.n===0);if(cueMissing)balls.unshift(makeBall(0,300,325));let msg='Έτοιμο για επόμενο χτύπημα.';if(poolModeV22==='9ball'){const legalFirst=targetBeforeShot==null||firstHitNumber===targetBeforeShot,ninePotted=pottedThisShot.includes(9);if(!legalFirst){msg=`Φάουλ: έπρεπε να χτυπήσεις πρώτα τη ${targetBeforeShot}.`;const cue=balls.find(b=>b.n===0);if(cue){cue.x=300;cue.y=325;cue.vx=cue.vy=0}}else if(ninePotted)msg='🏆 Νόμιμη 9 — ΚΕΡΔΙΣΕΣ ΤΟ 9-BALL!';else{const lo=lowestNine();msg=lo?`Σειρά: χτύπησε πρώτα τη μπάλα ${lo}.`:'Τέλος παρτίδας.'}}else if(pottedThisShot.length)msg=`Μπήκαν: ${pottedThisShot.join(', ')}.`;firstHitNumber=null;pottedThisShot=[];targetBeforeShot=null;const r=$q('#poolResult');if(r)r.textContent=msg;drawPool()}
    stepPool=function(){let moving=false;for(const b of balls){b.x+=b.vx;b.y+=b.vy;b.vx*=.986;b.vy*=.986;if(Math.abs(b.vx)+Math.abs(b.vy)>.07)moving=true;if(b.x<91){b.x=91;b.vx=Math.abs(b.vx)*.91}if(b.x>1109){b.x=1109;b.vx=-Math.abs(b.vx)*.91}if(b.y<91){b.y=91;b.vy=Math.abs(b.vy)*.91}if(b.y>559){b.y=559;b.vy=-Math.abs(b.vy)*.91}}for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){const a=balls[i],b=balls[j],dx=b.x-a.x,dy=b.y-a.y,dist=Math.hypot(dx,dy);if(dist>0&&dist<26){if(firstHitNumber==null){if(a.n===0&&b.n>0)firstHitNumber=b.n;else if(b.n===0&&a.n>0)firstHitNumber=a.n}const nx=dx/dist,ny=dy/dist,rel=(a.vx-b.vx)*nx+(a.vy-b.vy)*ny;if(rel>0){const impulse=rel*.98;a.vx-=impulse*nx;a.vy-=impulse*ny;b.vx+=impulse*nx;b.vy+=impulse*ny}const ov=26-dist;a.x-=nx*ov/2;a.y-=ny*ov/2;b.x+=nx*ov/2;b.y+=ny*ov/2}}const kept=[];for(const b of balls){if(inPocket(b)){if(b.n>0)pottedThisShot.push(b.n);continue}kept.push(b)}balls=kept;drawPool();if(moving)requestAnimationFrame(stepPool);else endShot()};
    const needleToPower=()=>.20+(needlePhase/124)*.80,needleLabel=()=>needlePower>.88?'MAX':needlePower>.62?'3':needlePower>.38?'2':'1';function animateNeedle(){needlePhase+=needleDir*1.55;if(needlePhase>=124){needlePhase=124;needleDir=-1}if(needlePhase<=0){needlePhase=0;needleDir=1}needlePower=needleToPower();const angle=-62+needlePhase,nd=$q('#swingNeedle');if(nd)nd.style.transform=`rotate(${angle}deg)`;const rd=$q('#swingReadout');if(rd)rd.textContent=`Ισχύς: ${needleLabel()}${needleLabel()==='MAX'?' — ΠΑΤΑ OK!':''}`;needleRAF=requestAnimationFrame(animateNeedle)}cancelAnimationFrame(needleRAF);animateNeedle();
    shootPool=function(){if(anim)return;const cue=balls.find(b=>b.n===0);if(!cue)return;anim=true;firstHitNumber=null;pottedThisShot=[];targetBeforeShot=poolModeV22==='9ball'?lowestNine():null;const spd=9+needlePower*17;cue.vx=Math.cos(aim)*spd;cue.vy=Math.sin(aim)*spd;try{tone(230,.05)}catch(e){};const r=$q('#poolResult');if(r)r.textContent=`Χτύπημα ${needleLabel()}...`;requestAnimationFrame(stepPool)};function aimLeft(){if(anim)return;aim-=.055;drawPool()}function aimRight(){if(anim)return;aim+=.055;drawPool()}
    $$q('.poolMode').forEach(b=>b.onclick=()=>{$$q('.poolMode').forEach(x=>x.classList.remove('activeMode'));b.classList.add('activeMode');poolModeV22=b.textContent.includes('9')?'9ball':'8ball';resetPool()});const topShoot=$q('#shootBtn');if(topShoot)topShoot.onclick=shootPool;$$q('[data-v22]').forEach(b=>b.onclick=()=>{const a=b.dataset.v22;if(a==='aimLeft')aimLeft();else if(a==='aimRight')aimRight();else if(a==='camPrev')prevCamera();else if(a==='camNext')nextCamera();else shootPool()});function handleDpad(a){if(!$q('#billiards.screen.active'))return false;if(a==='left')aimLeft();else if(a==='right')aimRight();else if(a==='up')prevCamera();else if(a==='down')nextCamera();else if(a==='ok')shootPool();else return false;return true}
    let lastNativeDpad=0;window.addEventListener('android-dpad',e=>{lastNativeDpad=performance.now();if(handleDpad(e.detail))e.preventDefault?.()});window.addEventListener('keydown',e=>{if(performance.now()-lastNativeDpad<140){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();return}const code=e.keyCode||e.which||0;let a=null;if(e.key==='ArrowLeft'||code===21||code===37)a='left';else if(e.key==='ArrowRight'||code===22||code===39)a='right';else if(e.key==='ArrowUp'||code===19||code===38)a='up';else if(e.key==='ArrowDown'||code===20||code===40)a='down';else if(e.key==='Enter'||e.key===' '||code===23||code===66)a='ok';if(a&&handleDpad(a)){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation()}},true);resetPool();
  }
})();