plugins {
    id 'com.android.application'
}

android {
    namespace 'com.kostas.geminibrowser'
    compileSdk 36

    defaultConfig {
        applicationId 'com.kostas.geminibrowser.finalv2'
        minSdk 29
        targetSdk 36
        versionCode 3
        versionName '3.0.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix ''
        }
        release {
            minifyEnabled false
        }
    }
}
