plugins { id 'com.android.application' }

android {
  namespace 'com.costas.eightiesyoutubev4'
  compileSdk 34
  defaultConfig {
    applicationId "com.costas.eightiesyoutubev4"
    minSdk 29
    targetSdk 34
    versionCode 4
    versionName "4.0"
  }
  buildTypes {
    debug { minifyEnabled false }
    release { minifyEnabled false }
  }
}
