plugins {
    id 'com.android.application'
}

android {
    namespace 'com.costas.builder'
    compileSdk 34

    defaultConfig {
        applicationId "com.costas.fmunlocktest"
        minSdk 23
        targetSdk 27
        versionCode 1
        versionName "1.0.0"
        resValue "string", "app_name", "FM Χωρίς Ακουστικά"
    }

    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
