plugins {
    id 'com.android.application'
}

android {
    namespace 'com.costas.builder'
    compileSdk 34

    defaultConfig {
        applicationId "com.costas.photomotionfreeai"
        minSdk 29
        targetSdk 34
        versionCode 1
        versionName "1.0"
        resValue "string", "app_name", "PhotoMotion Free AI"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}
