plugins {
    id 'com.android.application'
}

android {
    namespace 'com.costas.apkcontroller'
    compileSdk 34

    defaultConfig {
        applicationId "com.costas.apkcontroller"
        minSdk 29
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }
}
