plugins {
    id 'com.android.application'
}

android {
    namespace 'com.costas.globalmusictv'
    compileSdk 34

    defaultConfig {
        applicationId "com.costas.globalmusictv"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}
